const { contextBridge, ipcRenderer, shell, webFrame } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  openExternal: (url) => ipcRenderer.send('open-external', url),
  onSpots: (cb) => ipcRenderer.on('spots', (_e, data) => cb(data)),
  onSpotsError: (cb) => ipcRenderer.on('spots-error', (_e, msg) => cb(msg)),
  onCatStatus: (cb) => ipcRenderer.on('cat-status', (_e, s) => cb(s)),
  tune: (frequency, mode, bearing) => ipcRenderer.send('tune', { frequency, mode, bearing }),
  refresh: () => ipcRenderer.send('refresh'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  listPorts: () => ipcRenderer.invoke('list-ports'),
  listRigs: () => ipcRenderer.invoke('list-rigs'),
  testHamlib: (config) => ipcRenderer.invoke('test-hamlib', config),
  testSerialCat: (config) => ipcRenderer.invoke('test-serial-cat', config),
  testIcomCiv: (config) => ipcRenderer.invoke('test-icom-civ', config),
  connectCat: (target) => ipcRenderer.send('connect-cat', target),
  onCatFrequency: (cb) => ipcRenderer.on('cat-frequency', (_e, hz) => cb(hz)),
  onCatMode: (cb) => ipcRenderer.on('cat-mode', (_e, mode) => cb(mode)),
  onCatPower: (cb) => ipcRenderer.on('cat-power', (_e, watts) => cb(watts)),
  qrzLookup: (callsign) => ipcRenderer.invoke('qrz-lookup', callsign),
  qrzCheckSub: (force) => ipcRenderer.invoke('qrz-check-sub', force),
  qrzVerifyApiKey: (key) => ipcRenderer.invoke('qrz-verify-api-key', key),
  getReleaseNotes: (version) => ipcRenderer.invoke('get-release-notes', version),
  importAdif: () => ipcRenderer.invoke('import-adif'),
  parseAdif: () => ipcRenderer.invoke('parse-adif'),
  onDxccData: (cb) => ipcRenderer.on('dxcc-data', (_e, data) => cb(data)),
  onClusterStatus: (cb) => ipcRenderer.on('cluster-status', (_e, s) => cb(s)),
  onRbnSpots: (cb) => ipcRenderer.on('rbn-spots', (_e, data) => cb(data)),
  onRbnStatus: (cb) => ipcRenderer.on('rbn-status', (_e, s) => cb(s)),
  onPskrStatus: (cb) => ipcRenderer.on('pskr-status', (_e, s) => cb(s)),
  onAgStatus: (cb) => ipcRenderer.on('ag-status', (_e, s) => cb(s)),
  onAgAntennaNames: (cb) => ipcRenderer.on('ag-antenna-names', (_e, names) => cb(names)),
  onAgPortStatus: (cb) => ipcRenderer.on('ag-port-status', (_e, s) => cb(s)),
  clearRbn: () => ipcRenderer.send('rbn-clear'),
  onSolarData: (cb) => ipcRenderer.on('solar-data', (_e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, d) => cb(d)),
  onUpdaterActive: (cb) => ipcRenderer.on('updater-active', (_e, active) => cb(active)),
  onDownloadProgress: (cb) => ipcRenderer.on('update-download-progress', (_e, d) => cb(d)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_e, msg) => cb(msg)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', () => cb()),
  onUpdateUpToDate: (cb) => ipcRenderer.on('update-up-to-date', () => cb()),
  startDownload: () => ipcRenderer.send('start-download'),
  installUpdate: () => ipcRenderer.send('install-update'),
  checkForUpdates: () => ipcRenderer.send('check-for-updates'),
  onCatLog: (cb) => ipcRenderer.on('cat-log', (_e, msg) => cb(msg)),
  onWorkedQsos: (cb) => ipcRenderer.on('worked-qsos', (_e, data) => cb(data)),
  onWorkedParks: (cb) => ipcRenderer.on('worked-parks', (_e, data) => cb(data)),
  choosePotaParksFile: () => ipcRenderer.invoke('choose-pota-parks-file'),
  onWsjtxStatus: (cb) => ipcRenderer.on('wsjtx-status', (_e, s) => cb(s)),
  onWsjtxState: (cb) => ipcRenderer.on('wsjtx-state', (_e, s) => cb(s)),
  onWsjtxDecode: (cb) => ipcRenderer.on('wsjtx-decode', (_e, d) => cb(d)),
  onWsjtxClear: (cb) => ipcRenderer.on('wsjtx-clear', () => cb()),
  onWsjtxQsoLogged: (cb) => ipcRenderer.on('wsjtx-qso-logged', (_e, q) => cb(q)),
  onWsjtxActivatorQso: (cb) => ipcRenderer.on('wsjtx-activator-qso', (_e, c) => cb(c)),
  wsjtxReply: (decode) => ipcRenderer.send('wsjtx-reply', decode),
  wsjtxHaltTx: () => ipcRenderer.send('wsjtx-halt-tx'),
  saveQso: (qsoData) => ipcRenderer.invoke('save-qso', qsoData),
  quickRespot: (data) => ipcRenderer.invoke('quick-respot', data),
  sendClusterCommand: (text, nodeId) => ipcRenderer.invoke('send-cluster-command', text, nodeId),
  getRecentQsos: () => ipcRenderer.invoke('get-recent-qsos'),
  getAllQsos: () => ipcRenderer.invoke('get-all-qsos'),
  updateQso: (data) => ipcRenderer.invoke('update-qso', data),
  deleteQso: (idx) => ipcRenderer.invoke('delete-qso', idx),
  deleteQsosByMatch: (match) => ipcRenderer.invoke('delete-qsos-by-match', match),
  updateQsosByMatch: (data) => ipcRenderer.invoke('update-qsos-by-match', data),
  getDefaultLogPath: () => ipcRenderer.invoke('get-default-log-path'),
  chooseLogFile: (currentPath) => ipcRenderer.invoke('choose-log-file', currentPath),
  exportAdif: (qsos) => ipcRenderer.invoke('export-adif', qsos),
  onQrzData: (cb) => ipcRenderer.on('qrz-data', (_e, data) => cb(data)),
  onDonorCallsigns: (cb) => ipcRenderer.on('donor-callsigns', (_e, data) => cb(data)),
  onExpeditionCallsigns: (cb) => ipcRenderer.on('expedition-callsigns', (_e, data) => cb(data)),
  // Directory (HF Nets & SWL Broadcasts)
  onDirectoryData: (cb) => ipcRenderer.on('directory-data', (_e, data) => cb(data)),
  fetchDirectory: () => ipcRenderer.send('fetch-directory'),
  getDirectory: () => ipcRenderer.invoke('get-directory'),
  // Events system
  onActiveEvents: (cb) => ipcRenderer.on('active-events', (_e, data) => cb(data)),
  getActiveEvents: () => ipcRenderer.invoke('get-active-events'),
  setEventOptIn: (data) => ipcRenderer.invoke('set-event-optin', data),
  getEventProgress: (eventId) => ipcRenderer.invoke('get-event-progress', eventId),
  markEventRegion: (data) => ipcRenderer.invoke('mark-event-region', data),
  resetEventProgress: (eventId) => ipcRenderer.invoke('reset-event-progress', eventId),
  exportEventAdif: (data) => ipcRenderer.invoke('export-event-adif', data),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
  // Pop-out map
  popoutMapOpen: () => ipcRenderer.send('popout-map-open'),
  popoutMapClose: () => ipcRenderer.send('popout-map-close'),
  sendPopoutSpots: (data) => ipcRenderer.send('popout-map-spots', data),
  sendPopoutTuneArc: (data) => ipcRenderer.send('popout-map-tune-arc', data),
  sendPopoutHome: (data) => ipcRenderer.send('popout-map-home', data),
  sendPopoutTheme: (theme) => ipcRenderer.send('popout-map-theme', theme),
  sendColorblindMode: (enabled) => ipcRenderer.send('colorblind-mode', enabled),
  sendWcagMode: (enabled) => ipcRenderer.send('wcag-mode', enabled),
  onPopoutMapStatus: (cb) => ipcRenderer.on('popout-map-status', (_e, open) => cb(open)),
  onPopoutOpenLog: (cb) => ipcRenderer.on('popout-open-log', (_e, spot) => cb(spot)),
  // Pop-out QSO log
  qsoPopoutOpen: () => ipcRenderer.send('qso-popout-open'),
  qsoPopoutClose: () => ipcRenderer.send('qso-popout-close'),
  sendQsoPopoutTheme: (theme) => ipcRenderer.send('qso-popout-theme', theme),
  onQsoPopoutStatus: (cb) => ipcRenderer.on('qso-popout-status', (_e, open) => cb(open)),
  // Pop-out spots window
  spotsPopoutOpen: () => ipcRenderer.send('spots-popout-open'),
  spotsPopoutClose: () => ipcRenderer.send('spots-popout-close'),
  sendSpotsPopoutTheme: (theme) => ipcRenderer.send('spots-popout-theme', theme),
  onSpotsPopoutStatus: (cb) => ipcRenderer.on('spots-popout-status', (_e, open) => cb(open)),
  // DX Cluster terminal pop-out
  clusterPopoutOpen: () => ipcRenderer.send('cluster-popout-open'),
  clusterPopoutClose: () => ipcRenderer.send('cluster-popout-close'),
  sendClusterPopoutTheme: (theme) => ipcRenderer.send('cluster-popout-theme', theme),
  onClusterPopoutStatus: (cb) => ipcRenderer.on('cluster-popout-status', (_e, open) => cb(open)),
  // Activation map pop-out
  actmapPopoutOpen: () => ipcRenderer.send('actmap-popout-open'),
  actmapPopoutData: (data) => ipcRenderer.send('actmap-popout-data', data),
  actmapPopoutContact: (data) => ipcRenderer.send('actmap-popout-contact', data),
  actmapPopoutTheme: (theme) => ipcRenderer.send('actmap-popout-theme', theme),
  onActmapPopoutStatus: (cb) => ipcRenderer.on('actmap-popout-status', (_e, open) => cb(open)),
  // CW Keyer
  cwPaddleDit: (pressed) => ipcRenderer.send('cw-paddle-dit', pressed),
  cwPaddleDah: (pressed) => ipcRenderer.send('cw-paddle-dah', pressed),
  cwSetWpm: (wpm) => ipcRenderer.send('cw-set-wpm', wpm),
  cwStop: () => ipcRenderer.send('cw-stop'),
  // Activator mode — parks DB
  fetchParksDb: (prefix) => ipcRenderer.invoke('fetch-parks-db', prefix),
  searchParks: (query) => ipcRenderer.invoke('search-parks', query),
  getPark: (ref) => ipcRenderer.invoke('get-park', ref),
  parksDbStatus: () => ipcRenderer.invoke('parks-db-status'),
  exportActivationAdif: (data) => ipcRenderer.invoke('export-activation-adif', data),
  exportActivationAdifPerPark: (data) => ipcRenderer.invoke('export-activation-adif-perpark', data),
  getPastActivations: () => ipcRenderer.invoke('get-past-activations'),
  deleteActivation: (parkRef, date) => ipcRenderer.invoke('delete-activation', parkRef, date),
  resolveCallsignLocations: (callsigns) => ipcRenderer.invoke('resolve-callsign-locations', callsigns),
  captureActmapPopout: () => ipcRenderer.invoke('capture-actmap-popout'),
  captureMainWindowRect: (rect) => ipcRenderer.invoke('capture-main-window-rect', rect),
  saveShareImage: (data) => ipcRenderer.invoke('save-share-image', data),
  // Zoom
  setZoom: (factor) => webFrame.setZoomFactor(factor),
  getZoom: () => webFrame.getZoomFactor(),
  onCwKey: (cb) => ipcRenderer.on('cw-key', (_e, data) => cb(data)),
  onCwKeyerStatus: (cb) => ipcRenderer.on('cw-keyer-status', (_e, s) => cb(s)),
  onCwText: (cb) => ipcRenderer.on('cw-text', (_e, data) => cb(data)),
  // Remote Access
  getLocalIPs: () => ipcRenderer.invoke('get-local-ips'),
  // Club Station Mode
  chooseClubCsvFile: () => ipcRenderer.invoke('choose-club-csv-file'),
  previewClubCsv: (csvPath) => ipcRenderer.invoke('preview-club-csv', csvPath),
  hashClubPasswords: (csvPath) => ipcRenderer.invoke('hash-club-passwords', csvPath),
  createClubCsv: (rigNames) => ipcRenderer.invoke('create-club-csv', rigNames),
  // Rig Control Panel
  rigControl: (data) => ipcRenderer.invoke('rig-control', data),
  onRigState: (cb) => ipcRenderer.on('rig-state', (_e, state) => cb(state)),
  onRemoteTxState: (cb) => ipcRenderer.on('remote-tx-state', (_e, state) => cb(state)),
  onRemoteStatus: (cb) => ipcRenderer.on('remote-status', (_e, s) => cb(s)),
  onReloadPrefs: (cb) => ipcRenderer.on('reload-prefs', () => cb()),
});
